#!/bin/bash



fullName(){
  local first=$1
  local last=$2
  #return to caller. Echo/Print does not work inside functions.
  echo "first: $first. Last: $last"
}

#call it and assign
first="rick"
last="medina"
full=$( fullName "$first" "$last" )
echo $full
